<?php

use App\Models\Negara;
use Illuminate\Database\Seeder;
use Ramsey\Uuid\Uuid;

class NegaraTableSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataNegara = [
            [ 'negara' => 'Afghanistan', 'iso' => 'AF' ],
            [ 'negara' => 'Åland Islands', 'iso' => 'AX' ],
            [ 'negara' => 'Albania', 'iso' => 'AL' ],
            [ 'negara' => 'Algeria', 'iso' => 'DZ' ],
            [ 'negara' => 'American Samoa', 'iso' => 'AS' ],
            [ 'negara' => 'Andorra', 'iso' => 'AD' ],
            [ 'negara' => 'Angola', 'iso' => 'AO' ],
            [ 'negara' => 'Anguilla', 'iso' => 'AI' ],
            [ 'negara' => 'Antarctica', 'iso' => 'AQ' ],
            [ 'negara' => 'Antigua and Barbuda', 'iso' => 'AG' ],
            [ 'negara' => 'Argentina', 'iso' => 'AR' ],
            [ 'negara' => 'Armenia', 'iso' => 'AM' ],
            [ 'negara' => 'Aruba', 'iso' => 'AW' ],
            [ 'negara' => 'Australia', 'iso' => 'AU' ],
            [ 'negara' => 'Austria', 'iso' => 'AT' ],
            [ 'negara' => 'Azerbaijan', 'iso' => 'AZ' ],
            [ 'negara' => 'Bahamas', 'iso' => 'BS' ],
            [ 'negara' => 'Bahrain', 'iso' => 'BH' ],
            [ 'negara' => 'Bangladesh', 'iso' => 'BD' ],
            [ 'negara' => 'Barbados', 'iso' => 'BB' ],
            [ 'negara' => 'Belarus', 'iso' => 'BY' ],
            [ 'negara' => 'Belgium', 'iso' => 'BE' ],
            [ 'negara' => 'Belize', 'iso' => 'BZ' ],
            [ 'negara' => 'Benin', 'iso' => 'BJ' ],
            [ 'negara' => 'Bermuda', 'iso' => 'BM' ],
            [ 'negara' => 'Bhutan', 'iso' => 'BT' ],
            [ 'negara' => 'Bolivia', 'iso' => 'BO' ],
            [ 'negara' => 'Bosnia and Herzegovina', 'iso' => 'BA' ],
            [ 'negara' => 'Botswana', 'iso' => 'BW' ],
            [ 'negara' => 'Bouvet Island', 'iso' => 'BV' ],
            [ 'negara' => 'Brazil', 'iso' => 'BR' ],
            [ 'negara' => 'British Indian Ocean Territory', 'iso' => 'IO' ],
            [ 'negara' => 'Brunei Darussalam', 'iso' => 'BN' ],
            [ 'negara' => 'Bulgaria', 'iso' => 'BG' ],
            [ 'negara' => 'Burkina Faso', 'iso' => 'BF' ],
            [ 'negara' => 'Burundi', 'iso' => 'BI' ],
            [ 'negara' => 'Cambodia', 'iso' => 'KH' ],
            [ 'negara' => 'Cameroon', 'iso' => 'CM' ],
            [ 'negara' => 'Canada', 'iso' => 'CA' ],
            [ 'negara' => 'Cape Verde', 'iso' => 'CV' ],
            [ 'negara' => 'Cayman Islands', 'iso' => 'KY' ],
            [ 'negara' => 'Central African Republic', 'iso' => 'CF' ],
            [ 'negara' => 'Chad', 'iso' => 'TD' ],
            [ 'negara' => 'Chile', 'iso' => 'CL' ],
            [ 'negara' => 'China', 'iso' => 'CN' ],
            [ 'negara' => 'Christmas Island', 'iso' => 'CX' ],
            [ 'negara' => 'Cocos (Keeling) Islands', 'iso' => 'CC' ],
            [ 'negara' => 'Colombia', 'iso' => 'CO' ],
            [ 'negara' => 'Comoros', 'iso' => 'KM' ],
            [ 'negara' => 'Congo', 'iso' => 'CG' ],
            [ 'negara' => 'Congo, The Democratic Republic of the', 'iso' => 'CD' ],
            [ 'negara' => 'Cook Islands', 'iso' => 'CK' ],
            [ 'negara' => 'Costa Rica', 'iso' => 'CR' ],
            [ 'negara' => 'Cote D\'Ivoire', 'iso' => 'CI' ],
            [ 'negara' => 'Croatia', 'iso' => 'HR' ],
            [ 'negara' => 'Cuba', 'iso' => 'CU' ],
            [ 'negara' => 'Cyprus', 'iso' => 'CY' ],
            [ 'negara' => 'Czech Republic', 'iso' => 'CZ' ],
            [ 'negara' => 'Denmark', 'iso' => 'DK' ],
            [ 'negara' => 'Djibouti', 'iso' => 'DJ' ],
            [ 'negara' => 'Dominica', 'iso' => 'DM' ],
            [ 'negara' => 'Dominican Republic', 'iso' => 'DO' ],
            [ 'negara' => 'Ecuador', 'iso' => 'EC' ],
            [ 'negara' => 'Egypt', 'iso' => 'EG' ],
            [ 'negara' => 'El Salvador', 'iso' => 'SV' ],
            [ 'negara' => 'Equatorial Guinea', 'iso' => 'GQ' ],
            [ 'negara' => 'Eritrea', 'iso' => 'ER' ],
            [ 'negara' => 'Estonia', 'iso' => 'EE' ],
            [ 'negara' => 'Ethiopia', 'iso' => 'ET' ],
            [ 'negara' => 'Falkland Islands (Malvinas)', 'iso' => 'FK' ],
            [ 'negara' => 'Faroe Islands', 'iso' => 'FO' ],
            [ 'negara' => 'Fiji', 'iso' => 'FJ' ],
            [ 'negara' => 'Finland', 'iso' => 'FI' ],
            [ 'negara' => 'France', 'iso' => 'FR' ],
            [ 'negara' => 'French Guiana', 'iso' => 'GF' ],
            [ 'negara' => 'French Polynesia', 'iso' => 'PF' ],
            [ 'negara' => 'French Southern Territories', 'iso' => 'TF' ],
            [ 'negara' => 'Gabon', 'iso' => 'GA' ],
            [ 'negara' => 'Gambia', 'iso' => 'GM' ],
            [ 'negara' => 'Georgia', 'iso' => 'GE' ],
            [ 'negara' => 'Germany', 'iso' => 'DE' ],
            [ 'negara' => 'Ghana', 'iso' => 'GH' ],
            [ 'negara' => 'Gibraltar', 'iso' => 'GI' ],
            [ 'negara' => 'Greece', 'iso' => 'GR' ],
            [ 'negara' => 'Greenland', 'iso' => 'GL' ],
            [ 'negara' => 'Grenada', 'iso' => 'GD' ],
            [ 'negara' => 'Guadeloupe', 'iso' => 'GP' ],
            [ 'negara' => 'Guam', 'iso' => 'GU' ],
            [ 'negara' => 'Guatemala', 'iso' => 'GT' ],
            [ 'negara' => 'Guernsey', 'iso' => 'GG' ],
            [ 'negara' => 'Guinea', 'iso' => 'GN' ],
            [ 'negara' => 'Guinea-Bissau', 'iso' => 'GW' ],
            [ 'negara' => 'Guyana', 'iso' => 'GY' ],
            [ 'negara' => 'Haiti', 'iso' => 'HT' ],
            [ 'negara' => 'Heard Island and Mcdonald Islands', 'iso' => 'HM' ],
            [ 'negara' => 'Holy See (Vatican City State)', 'iso' => 'VA' ],
            [ 'negara' => 'Honduras', 'iso' => 'HN' ],
            [ 'negara' => 'Hong Kong', 'iso' => 'HK' ],
            [ 'negara' => 'Hungary', 'iso' => 'HU' ],
            [ 'negara' => 'Iceland', 'iso' => 'IS' ],
            [ 'negara' => 'India', 'iso' => 'IN' ],
            [ 'negara' => 'Indonesia', 'iso' => 'ID' ],
            [ 'negara' => 'Iran, Islamic Republic Of', 'iso' => 'IR' ],
            [ 'negara' => 'Iraq', 'iso' => 'IQ' ],
            [ 'negara' => 'Ireland', 'iso' => 'IE' ],
            [ 'negara' => 'Isle of Man', 'iso' => 'IM' ],
            [ 'negara' => 'Israel', 'iso' => 'IL' ],
            [ 'negara' => 'Italy', 'iso' => 'IT' ],
            [ 'negara' => 'Jamaica', 'iso' => 'JM' ],
            [ 'negara' => 'Japan', 'iso' => 'JP' ],
            [ 'negara' => 'Jersey', 'iso' => 'JE' ],
            [ 'negara' => 'Jordan', 'iso' => 'JO' ],
            [ 'negara' => 'Kazakhstan', 'iso' => 'KZ' ],
            [ 'negara' => 'Kenya', 'iso' => 'KE' ],
            [ 'negara' => 'Kiribati', 'iso' => 'KI' ],
            [ 'negara' => 'Democratic People\'s Republic of Korea', 'iso' => 'KP' ],
            [ 'negara' => 'Korea, Republic of', 'iso' => 'KR' ],
            [ 'negara' => 'Kosovo', 'iso' => 'XK' ],
            [ 'negara' => 'Kuwait', 'iso' => 'KW' ],
            [ 'negara' => 'Kyrgyzstan', 'iso' => 'KG' ],
            [ 'negara' => 'Lao People\'s Democratic Republic', 'iso' => 'LA' ],
            [ 'negara' => 'Latvia', 'iso' => 'LV' ],
            [ 'negara' => 'Lebanon', 'iso' => 'LB' ],
            [ 'negara' => 'Lesotho', 'iso' => 'LS' ],
            [ 'negara' => 'Liberia', 'iso' => 'LR' ],
            [ 'negara' => 'Libyan Arab Jamahiriya', 'iso' => 'LY' ],
            [ 'negara' => 'Liechtenstein', 'iso' => 'LI' ],
            [ 'negara' => 'Lithuania', 'iso' => 'LT' ],
            [ 'negara' => 'Luxembourg', 'iso' => 'LU' ],
            [ 'negara' => 'Macao', 'iso' => 'MO' ],
            [ 'negara' => 'Macedonia, The Former Yugoslav Republic of', 'iso' => 'MK' ],
            [ 'negara' => 'Madagascar', 'iso' => 'MG' ],
            [ 'negara' => 'Malawi', 'iso' => 'MW' ],
            [ 'negara' => 'Malaysia', 'iso' => 'MY' ],
            [ 'negara' => 'Maldives', 'iso' => 'MV' ],
            [ 'negara' => 'Mali', 'iso' => 'ML' ],
            [ 'negara' => 'Malta', 'iso' => 'MT' ],
            [ 'negara' => 'Marshall Islands', 'iso' => 'MH' ],
            [ 'negara' => 'Martinique', 'iso' => 'MQ' ],
            [ 'negara' => 'Mauritania', 'iso' => 'MR' ],
            [ 'negara' => 'Mauritius', 'iso' => 'MU' ],
            [ 'negara' => 'Mayotte', 'iso' => 'YT' ],
            [ 'negara' => 'Mexico', 'iso' => 'MX' ],
            [ 'negara' => 'Micronesia, Federated States of', 'iso' => 'FM' ],
            [ 'negara' => 'Moldova, Republic of', 'iso' => 'MD' ],
            [ 'negara' => 'Monaco', 'iso' => 'MC' ],
            [ 'negara' => 'Mongolia', 'iso' => 'MN' ],
            [ 'negara' => 'Montenegro', 'iso' => 'ME' ],
            [ 'negara' => 'Montserrat', 'iso' => 'MS' ],
            [ 'negara' => 'Morocco', 'iso' => 'MA' ],
            [ 'negara' => 'Mozambique', 'iso' => 'MZ' ],
            [ 'negara' => 'Myanmar', 'iso' => 'MM' ],
            [ 'negara' => 'Namibia', 'iso' => 'NA' ],
            [ 'negara' => 'Nauru', 'iso' => 'NR' ],
            [ 'negara' => 'Nepal', 'iso' => 'NP' ],
            [ 'negara' => 'Netherlands', 'iso' => 'NL' ],
            [ 'negara' => 'Netherlands Antilles', 'iso' => 'AN' ],
            [ 'negara' => 'New Caledonia', 'iso' => 'NC' ],
            [ 'negara' => 'New Zealand', 'iso' => 'NZ' ],
            [ 'negara' => 'Nicaragua', 'iso' => 'NI' ],
            [ 'negara' => 'Niger', 'iso' => 'NE' ],
            [ 'negara' => 'Nigeria', 'iso' => 'NG' ],
            [ 'negara' => 'Niue', 'iso' => 'NU' ],
            [ 'negara' => 'Norfolk Island', 'iso' => 'NF' ],
            [ 'negara' => 'Northern Mariana Islands', 'iso' => 'MP' ],
            [ 'negara' => 'Norway', 'iso' => 'NO' ],
            [ 'negara' => 'Oman', 'iso' => 'OM' ],
            [ 'negara' => 'Pakistan', 'iso' => 'PK' ],
            [ 'negara' => 'Palau', 'iso' => 'PW' ],
            [ 'negara' => 'Palestinian Territory, Occupied', 'iso' => 'PS' ],
            [ 'negara' => 'Panama', 'iso' => 'PA' ],
            [ 'negara' => 'Papua New Guinea', 'iso' => 'PG' ],
            [ 'negara' => 'Paraguay', 'iso' => 'PY' ],
            [ 'negara' => 'Peru', 'iso' => 'PE' ],
            [ 'negara' => 'Philippines', 'iso' => 'PH' ],
            [ 'negara' => 'Pitcairn', 'iso' => 'PN' ],
            [ 'negara' => 'Poland', 'iso' => 'PL' ],
            [ 'negara' => 'Portugal', 'iso' => 'PT' ],
            [ 'negara' => 'Puerto Rico', 'iso' => 'PR' ],
            [ 'negara' => 'Qatar', 'iso' => 'QA' ],
            [ 'negara' => 'Reunion', 'iso' => 'RE' ],
            [ 'negara' => 'Romania', 'iso' => 'RO' ],
            [ 'negara' => 'Russian Federation', 'iso' => 'RU' ],
            [ 'negara' => 'Rwanda', 'iso' => 'RW' ],
            [ 'negara' => 'Saint Helena', 'iso' => 'SH' ],
            [ 'negara' => 'Saint Kitts and Nevis', 'iso' => 'KN' ],
            [ 'negara' => 'Saint Lucia', 'iso' => 'LC' ],
            [ 'negara' => 'Saint Pierre and Miquelon', 'iso' => 'PM' ],
            [ 'negara' => 'Saint Vincent and the Grenadines', 'iso' => 'VC' ],
            [ 'negara' => 'Samoa', 'iso' => 'WS' ],
            [ 'negara' => 'San Marino', 'iso' => 'SM' ],
            [ 'negara' => 'Sao Tome and Principe', 'iso' => 'ST' ],
            [ 'negara' => 'Saudi Arabia', 'iso' => 'SA' ],
            [ 'negara' => 'Senegal', 'iso' => 'SN' ],
            [ 'negara' => 'Serbia', 'iso' => 'RS' ],
            [ 'negara' => 'Seychelles', 'iso' => 'SC' ],
            [ 'negara' => 'Sierra Leone', 'iso' => 'SL' ],
            [ 'negara' => 'Singapore', 'iso' => 'SG' ],
            [ 'negara' => 'Slovakia', 'iso' => 'SK' ],
            [ 'negara' => 'Slovenia', 'iso' => 'SI' ],
            [ 'negara' => 'Solomon Islands', 'iso' => 'SB' ],
            [ 'negara' => 'Somalia', 'iso' => 'SO' ],
            [ 'negara' => 'South Africa', 'iso' => 'ZA' ],
            [ 'negara' => 'South Georgia and the South Sandwich Islands', 'iso' => 'GS' ],
            [ 'negara' => 'Spain', 'iso' => 'ES' ],
            [ 'negara' => 'Sri Lanka', 'iso' => 'LK' ],
            [ 'negara' => 'Sudan', 'iso' => 'SD' ],
            [ 'negara' => 'Suriname', 'iso' => 'SR' ],
            [ 'negara' => 'Svalbard and Jan Mayen', 'iso' => 'SJ' ],
            [ 'negara' => 'Swaziland', 'iso' => 'SZ' ],
            [ 'negara' => 'Sweden', 'iso' => 'SE' ],
            [ 'negara' => 'Switzerland', 'iso' => 'CH' ],
            [ 'negara' => 'Syrian Arab Republic', 'iso' => 'SY' ],
            [ 'negara' => 'Taiwan', 'iso' => 'TW' ],
            [ 'negara' => 'Tajikistan', 'iso' => 'TJ' ],
            [ 'negara' => 'Tanzania, United Republic of', 'iso' => 'TZ' ],
            [ 'negara' => 'Thailand', 'iso' => 'TH' ],
            [ 'negara' => 'Timor-Leste', 'iso' => 'TL' ],
            [ 'negara' => 'Togo', 'iso' => 'TG' ],
            [ 'negara' => 'Tokelau', 'iso' => 'TK' ],
            [ 'negara' => 'Tonga', 'iso' => 'TO' ],
            [ 'negara' => 'Trinidad and Tobago', 'iso' => 'TT' ],
            [ 'negara' => 'Tunisia', 'iso' => 'TN' ],
            [ 'negara' => 'Turkey', 'iso' => 'TR' ],
            [ 'negara' => 'Turkmenistan', 'iso' => 'TM' ],
            [ 'negara' => 'Turks and Caicos Islands', 'iso' => 'TC' ],
            [ 'negara' => 'Tuvalu', 'iso' => 'TV' ],
            [ 'negara' => 'Uganda', 'iso' => 'UG' ],
            [ 'negara' => 'Ukraine', 'iso' => 'UA' ],
            [ 'negara' => 'United Arab Emirates', 'iso' => 'AE' ],
            [ 'negara' => 'United Kingdom', 'iso' => 'GB' ],
            [ 'negara' => 'United States', 'iso' => 'US' ],
            [ 'negara' => 'United States Minor Outlying Islands', 'iso' => 'UM' ],
            [ 'negara' => 'Uruguay', 'iso' => 'UY' ],
            [ 'negara' => 'Uzbekistan', 'iso' => 'UZ' ],
            [ 'negara' => 'Vanuatu', 'iso' => 'VU' ],
            [ 'negara' => 'Venezuela', 'iso' => 'VE' ],
            [ 'negara' => 'Viet Nam', 'iso' => 'VN' ],
            [ 'negara' => 'Virgin Islands, British', 'iso' => 'VG' ],
            [ 'negara' => 'Virgin Islands, U.S.', 'iso' => 'VI' ],
            [ 'negara' => 'Wallis and Futuna', 'iso' => 'WF' ],
            [ 'negara' => 'Western Sahara', 'iso' => 'EH' ],
            [ 'negara' => 'Yemen', 'iso' => 'YE' ],
            [ 'negara' => 'Zambia', 'iso' => 'ZM' ],
            [ 'negara' => 'Zimbabwe', 'iso' => 'ZW' ]
        ];

        foreach ($dataNegara as $item) {
            Negara::create([
                'id_negara' => Uuid::uuid4()->toString(),
                'iso'       => $item['iso'],
                'negara'    => $item['negara']
            ]);
        }
    }
}
